language: python

python:
- "3.6"

install:
- pip install websocket-client

script:
- python -m unittest discover

deploy:
  provider: pypi
  user: "Kai-Bailey"
  password:
    secure: guSyRyd7L71uvzTFvbjZXFGJZH2wW4hFT2bD54oq31zkhbpd1sxBXayk9Po/ygQV48EUEdvgMcUTFLwtkAC/eS3FDygdfnLV6Evm0F7HupUUWeH9+Apw/rN3f6o9CkQ98L95Zy6kXibZZevUhllPClYuY8IShYAoGQtql4wgh1YfUtwvyC+r3AjTOKaxY7NCLOOj8ACIWDXGEPuocvSUwKN8S+UoOApTRN+Qx50suN/9JXLdRBRT9Izh2G0r8EGbpumqvP8hkNGEOj/5TEwxJyVmgq/UZOypv/x8BxS+SAkbnNwzVwVG1wDVXHYkLgbX8SSPiq8JYLjDaAIkhw4OGZ8eSJZPSkvPYehms7rbBBX7e9wMt9KmrbXNNa1fUw3FRDiUII/qDzA0ze7vNRcGoim9xn4jwaRTScOopH1eXN8VgUpXBhdKlb2Sbm6Z2dEFyTqwdbCL9XGdzqRve+rcW9fMR8d343+Fk7Fp1btSh3I6fcXtbjHGygv9t45ioAiwN7RjVB431khqr/lVMsY/YCfoqCqc9wqlFDheI7VNHXbDzk6mKb6ie0F3QEoCCMwKeDtRrtT7Re5I/PauBKSzjjwuN3602jBP9FjKNTNiFTSq+bvFeKj6Pp8nSKRIVxGGPO+wbkPEmtb6JanU4X+4uYlnNlZCPZL+Optco4v0QNk=
